//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomrin.Omrin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AansluitingValidatie", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier")]
    [System.SerializableAttribute()]
    public partial class AansluitingValidatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AansluitingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HuistnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Stomrin.Omrin.AansluitingStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StraatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToevoegingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WoonplaatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AansluitingID {
            get {
                return this.AansluitingIDField;
            }
            set {
                if ((this.AansluitingIDField.Equals(value) != true)) {
                    this.AansluitingIDField = value;
                    this.RaisePropertyChanged("AansluitingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Huistnummer {
            get {
                return this.HuistnummerField;
            }
            set {
                if ((this.HuistnummerField.Equals(value) != true)) {
                    this.HuistnummerField = value;
                    this.RaisePropertyChanged("Huistnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Stomrin.Omrin.AansluitingStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Straat {
            get {
                return this.StraatField;
            }
            set {
                if ((object.ReferenceEquals(this.StraatField, value) != true)) {
                    this.StraatField = value;
                    this.RaisePropertyChanged("Straat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Toevoeging {
            get {
                return this.ToevoegingField;
            }
            set {
                if ((object.ReferenceEquals(this.ToevoegingField, value) != true)) {
                    this.ToevoegingField = value;
                    this.RaisePropertyChanged("Toevoeging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Woonplaats {
            get {
                return this.WoonplaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.WoonplaatsField, value) != true)) {
                    this.WoonplaatsField = value;
                    this.RaisePropertyChanged("Woonplaats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AansluitingStatus", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier")]
    public enum AansluitingStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        valid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        notvalid = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderJarenResult", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    [System.SerializableAttribute()]
    public partial class KalenderJarenResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] JarenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Jaren {
            get {
                return this.JarenField;
            }
            set {
                if ((object.ReferenceEquals(this.JarenField, value) != true)) {
                    this.JarenField = value;
                    this.RaisePropertyChanged("Jaren");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderObject", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    [System.SerializableAttribute()]
    public partial class KalenderObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Stomrin.Omrin.KalenderGroepObject[] GroepenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JaarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Stomrin.Omrin.KalenderGroepObject[] Groepen {
            get {
                return this.GroepenField;
            }
            set {
                if ((object.ReferenceEquals(this.GroepenField, value) != true)) {
                    this.GroepenField = value;
                    this.RaisePropertyChanged("Groepen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Jaar {
            get {
                return this.JaarField;
            }
            set {
                if ((this.JaarField.Equals(value) != true)) {
                    this.JaarField = value;
                    this.RaisePropertyChanged("Jaar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderGroepObject", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    [System.SerializableAttribute()]
    public partial class KalenderGroepObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AfbeeldingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Stomrin.Omrin.KalenderGroepDatum[] DatumsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvgingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string info2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Afbeelding {
            get {
                return this.AfbeeldingField;
            }
            set {
                if ((object.ReferenceEquals(this.AfbeeldingField, value) != true)) {
                    this.AfbeeldingField = value;
                    this.RaisePropertyChanged("Afbeelding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Stomrin.Omrin.KalenderGroepDatum[] Datums {
            get {
                return this.DatumsField;
            }
            set {
                if ((object.ReferenceEquals(this.DatumsField, value) != true)) {
                    this.DatumsField = value;
                    this.RaisePropertyChanged("Datums");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijvging {
            get {
                return this.OmschrijvgingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvgingField, value) != true)) {
                    this.OmschrijvgingField = value;
                    this.RaisePropertyChanged("Omschrijvging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string info2 {
            get {
                return this.info2Field;
            }
            set {
                if ((object.ReferenceEquals(this.info2Field, value) != true)) {
                    this.info2Field = value;
                    this.RaisePropertyChanged("info2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderGroepDatum", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    [System.SerializableAttribute()]
    public partial class KalenderGroepDatum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DagSoortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DagSoort {
            get {
                return this.DagSoortField;
            }
            set {
                if ((object.ReferenceEquals(this.DagSoortField, value) != true)) {
                    this.DagSoortField = value;
                    this.RaisePropertyChanged("DagSoort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="Omrin.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidateAansluiting", ReplyAction="urn:Service1/ValidateAansluitingResponse")]
        Stomrin.Omrin.AansluitingValidatie ValidateAansluiting(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidateAansluiting", ReplyAction="urn:Service1/ValidateAansluitingResponse")]
        System.Threading.Tasks.Task<Stomrin.Omrin.AansluitingValidatie> ValidateAansluitingAsync(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidAdres", ReplyAction="urn:Service1/ValidAdresResponse")]
        int ValidAdres(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidAdres", ReplyAction="urn:Service1/ValidAdresResponse")]
        System.Threading.Tasks.Task<int> ValidAdresAsync(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalenderJaren", ReplyAction="urn:Service1/GetKalenderJarenResponse")]
        Stomrin.Omrin.KalenderJarenResult GetKalenderJaren(int aansluitingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalenderJaren", ReplyAction="urn:Service1/GetKalenderJarenResponse")]
        System.Threading.Tasks.Task<Stomrin.Omrin.KalenderJarenResult> GetKalenderJarenAsync(int aansluitingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalender", ReplyAction="urn:Service1/GetKalenderResponse")]
        Stomrin.Omrin.KalenderObject GetKalender(int aansluitingID, int jaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalender", ReplyAction="urn:Service1/GetKalenderResponse")]
        System.Threading.Tasks.Task<Stomrin.Omrin.KalenderObject> GetKalenderAsync(int aansluitingID, int jaar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : Stomrin.Omrin.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Stomrin.Omrin.Service1>, Stomrin.Omrin.Service1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Stomrin.Omrin.AansluitingValidatie ValidateAansluiting(string Postcode, int Huisnummer, string Toevoeging) {
            return base.Channel.ValidateAansluiting(Postcode, Huisnummer, Toevoeging);
        }
        
        public System.Threading.Tasks.Task<Stomrin.Omrin.AansluitingValidatie> ValidateAansluitingAsync(string Postcode, int Huisnummer, string Toevoeging) {
            return base.Channel.ValidateAansluitingAsync(Postcode, Huisnummer, Toevoeging);
        }
        
        public int ValidAdres(string Postcode, int Huisnummer, string Toevoeging) {
            return base.Channel.ValidAdres(Postcode, Huisnummer, Toevoeging);
        }
        
        public System.Threading.Tasks.Task<int> ValidAdresAsync(string Postcode, int Huisnummer, string Toevoeging) {
            return base.Channel.ValidAdresAsync(Postcode, Huisnummer, Toevoeging);
        }
        
        public Stomrin.Omrin.KalenderJarenResult GetKalenderJaren(int aansluitingID) {
            return base.Channel.GetKalenderJaren(aansluitingID);
        }
        
        public System.Threading.Tasks.Task<Stomrin.Omrin.KalenderJarenResult> GetKalenderJarenAsync(int aansluitingID) {
            return base.Channel.GetKalenderJarenAsync(aansluitingID);
        }
        
        public Stomrin.Omrin.KalenderObject GetKalender(int aansluitingID, int jaar) {
            return base.Channel.GetKalender(aansluitingID, jaar);
        }
        
        public System.Threading.Tasks.Task<Stomrin.Omrin.KalenderObject> GetKalenderAsync(int aansluitingID, int jaar) {
            return base.Channel.GetKalenderAsync(aansluitingID, jaar);
        }
    }
}
