//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omrin
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AansluitingValidatie", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier")]
    internal partial class AansluitingValidatie : object
    {
        
        private int AansluitingIDField;
        
        private int HuistnummerField;
        
        private string PostcodeField;
        
        private Omrin.AansluitingStatus StatusField;
        
        private string StraatField;
        
        private string ToevoegingField;
        
        private string WoonplaatsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int AansluitingID
        {
            get
            {
                return this.AansluitingIDField;
            }
            set
            {
                this.AansluitingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Huistnummer
        {
            get
            {
                return this.HuistnummerField;
            }
            set
            {
                this.HuistnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Postcode
        {
            get
            {
                return this.PostcodeField;
            }
            set
            {
                this.PostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Omrin.AansluitingStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straat
        {
            get
            {
                return this.StraatField;
            }
            set
            {
                this.StraatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Toevoeging
        {
            get
            {
                return this.ToevoegingField;
            }
            set
            {
                this.ToevoegingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Woonplaats
        {
            get
            {
                return this.WoonplaatsField;
            }
            set
            {
                this.WoonplaatsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AansluitingStatus", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier")]
    internal enum AansluitingStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        valid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        notvalid = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderJarenResult", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    internal partial class KalenderJarenResult : object
    {
        
        private int[] JarenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int[] Jaren
        {
            get
            {
                return this.JarenField;
            }
            set
            {
                this.JarenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderObject", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    internal partial class KalenderObject : object
    {
        
        private string CodeField;
        
        private Omrin.KalenderGroepObject[] GroepenField;
        
        private int JaarField;
        
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Omrin.KalenderGroepObject[] Groepen
        {
            get
            {
                return this.GroepenField;
            }
            set
            {
                this.GroepenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Jaar
        {
            get
            {
                return this.JaarField;
            }
            set
            {
                this.JaarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Omschrijving
        {
            get
            {
                return this.OmschrijvingField;
            }
            set
            {
                this.OmschrijvingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderGroepObject", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    internal partial class KalenderGroepObject : object
    {
        
        private string AfbeeldingField;
        
        private Omrin.KalenderGroepDatum[] DatumsField;
        
        private string InfoField;
        
        private string OmschrijvgingField;
        
        private string info2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Afbeelding
        {
            get
            {
                return this.AfbeeldingField;
            }
            set
            {
                this.AfbeeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Omrin.KalenderGroepDatum[] Datums
        {
            get
            {
                return this.DatumsField;
            }
            set
            {
                this.DatumsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Omschrijvging
        {
            get
            {
                return this.OmschrijvgingField;
            }
            set
            {
                this.OmschrijvgingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string info2
        {
            get
            {
                return this.info2Field;
            }
            set
            {
                this.info2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KalenderGroepDatum", Namespace="http://schemas.datacontract.org/2004/07/HHAMiddleTier.Dto.Kalender")]
    internal partial class KalenderGroepDatum : object
    {
        
        private string DagSoortField;
        
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DagSoort
        {
            get
            {
                return this.DagSoortField;
            }
            set
            {
                this.DagSoortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Datum
        {
            get
            {
                return this.DatumField;
            }
            set
            {
                this.DatumField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="Omrin.Service1")]
    internal interface Service1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidateAansluiting", ReplyAction="urn:Service1/ValidateAansluitingResponse")]
        Omrin.AansluitingValidatie ValidateAansluiting(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidateAansluiting", ReplyAction="urn:Service1/ValidateAansluitingResponse")]
        System.Threading.Tasks.Task<Omrin.AansluitingValidatie> ValidateAansluitingAsync(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidAdres", ReplyAction="urn:Service1/ValidAdresResponse")]
        int ValidAdres(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/ValidAdres", ReplyAction="urn:Service1/ValidAdresResponse")]
        System.Threading.Tasks.Task<int> ValidAdresAsync(string Postcode, int Huisnummer, string Toevoeging);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalenderJaren", ReplyAction="urn:Service1/GetKalenderJarenResponse")]
        Omrin.KalenderJarenResult GetKalenderJaren(int aansluitingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalenderJaren", ReplyAction="urn:Service1/GetKalenderJarenResponse")]
        System.Threading.Tasks.Task<Omrin.KalenderJarenResult> GetKalenderJarenAsync(int aansluitingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalender", ReplyAction="urn:Service1/GetKalenderResponse")]
        Omrin.KalenderObject GetKalender(int aansluitingID, int jaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/GetKalender", ReplyAction="urn:Service1/GetKalenderResponse")]
        System.Threading.Tasks.Task<Omrin.KalenderObject> GetKalenderAsync(int aansluitingID, int jaar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    internal interface Service1Channel : Omrin.Service1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    internal partial class Service1Client : System.ServiceModel.ClientBase<Omrin.Service1>, Omrin.Service1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_Service1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Omrin.AansluitingValidatie ValidateAansluiting(string Postcode, int Huisnummer, string Toevoeging)
        {
            return base.Channel.ValidateAansluiting(Postcode, Huisnummer, Toevoeging);
        }
        
        public System.Threading.Tasks.Task<Omrin.AansluitingValidatie> ValidateAansluitingAsync(string Postcode, int Huisnummer, string Toevoeging)
        {
            return base.Channel.ValidateAansluitingAsync(Postcode, Huisnummer, Toevoeging);
        }
        
        public int ValidAdres(string Postcode, int Huisnummer, string Toevoeging)
        {
            return base.Channel.ValidAdres(Postcode, Huisnummer, Toevoeging);
        }
        
        public System.Threading.Tasks.Task<int> ValidAdresAsync(string Postcode, int Huisnummer, string Toevoeging)
        {
            return base.Channel.ValidAdresAsync(Postcode, Huisnummer, Toevoeging);
        }
        
        public Omrin.KalenderJarenResult GetKalenderJaren(int aansluitingID)
        {
            return base.Channel.GetKalenderJaren(aansluitingID);
        }
        
        public System.Threading.Tasks.Task<Omrin.KalenderJarenResult> GetKalenderJarenAsync(int aansluitingID)
        {
            return base.Channel.GetKalenderJarenAsync(aansluitingID);
        }
        
        public Omrin.KalenderObject GetKalender(int aansluitingID, int jaar)
        {
            return base.Channel.GetKalender(aansluitingID, jaar);
        }
        
        public System.Threading.Tasks.Task<Omrin.KalenderObject> GetKalenderAsync(int aansluitingID, int jaar)
        {
            return base.Channel.GetKalenderAsync(aansluitingID, jaar);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_Service1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_Service1))
            {
                return new System.ServiceModel.EndpointAddress("http://lwd-dmz01:7980/burgerportal/ServiceKalender.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_Service1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.CustomBinding_Service1);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_Service1,
        }
    }
}
